
open Http_server

(* ---- HTML renderer ------------------------------------------------------ *)

let build_interactive_html lmod lmeth rmod rmeth =
  let buf = Buffer.create 8192 in
  let p fmt = Printf.bprintf buf fmt in
  p "<!DOCTYPE html>\n";
  p "<html lang=\"en\">\n";
  p "<head>\n";
  p "  <meta charset=\"utf-8\">\n";
  p "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
  p "  <title>Interactive Alignment: %s.%s | %s.%s</title>\n" lmod lmeth rmod rmeth;
  p "  <style>\n";
  p "    :root{--bg:#0f1115;--bg2:#171a21;--fg:#d7dde8;--muted:#9aa8be;--accent:#56b6c2;--ok:#7bd88f;--warn:#ffcb6b;--bad:#ff6b6b;--line:#2a3040}\n";
  p "    *{box-sizing:border-box} body{margin:0;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:radial-gradient(1200px 600px at 85%% -20%%,#223046 0%%,var(--bg) 45%%),var(--bg);color:var(--fg)}\n";
  p "    .wrap{max-width:1200px;margin:0 auto;padding:1rem} h1{font-size:1.05rem;margin:.2rem 0 1rem;color:#b8e3ff}\n";
  p "    .grid{display:grid;grid-template-columns:360px 1fr;gap:1rem} @media (max-width:960px){.grid{grid-template-columns:1fr}}\n";
  p "    .panel{background:linear-gradient(180deg,var(--bg2),#12151c);border:1px solid var(--line);border-radius:10px;padding:.8rem}\n";
  p "    .row{display:flex;gap:.5rem;align-items:center;flex-wrap:wrap;margin:.45rem 0} label{font-size:.82rem;color:var(--muted)}\n";
  p "    input,select,button{border-radius:7px;border:1px solid #3a4256;background:#0d1016;color:var(--fg);padding:.45rem .55rem;font:inherit;font-size:.86rem}\n";
  p "    input{flex:1 1 150px} button{cursor:pointer} button:hover{border-color:#54617e} .primary{border-color:#2f6f79;color:#b9f1f8}\n";
  p "    .danger{border-color:#7a2f2f;color:#ffbbbb} .good{border-color:#2f7a4b;color:#c9f9d4}\n";
  p "    #status{font-size:.82rem;color:var(--muted);min-height:1.2rem} #status.ok{color:var(--ok)} #status.err{color:var(--bad)}\n";
  p "    .code{display:table;border-collapse:collapse;width:100%%} .line{display:table-row}\n";
  p "    .ln{display:table-cell;text-align:right;padding:0 .8rem 0 0;color:#73809a;user-select:none;border-right:1px solid #2d3445;min-width:3em;cursor:pointer}\n";
  p "    .src{display:table-cell;padding:0 0 0 .8rem;white-space:pre-wrap;word-break:break-word}\n";
  p "    #suggestions{display:flex;flex-direction:column;gap:.35rem;max-height:280px;overflow:auto}\n";
  p "    .sitem{display:flex;justify-content:space-between;gap:.5rem;align-items:center;border:1px solid #2f3749;border-radius:8px;padding:.4rem .5rem;font-size:.82rem}\n";
  p "    .mono{font-family:inherit} a{color:#9cdcf7}\n";
  p "  </style>\n";
  p "</head>\n";
  p "<body>\n";
  p "  <div class=\"wrap\">\n";
  p "    <h1>Interactive Alignment: %s.%s | %s.%s</h1>\n" lmod lmeth rmod rmeth;
  p "    <div class=\"grid\">\n";
  p "      <section class=\"panel\">\n";
  p "        <div class=\"row\"><label for=\"path\">Path</label><input id=\"path\" placeholder=\"e.g. 0.1 (empty = root)\"></div>\n";
  p "        <div class=\"row\"><label for=\"rule\">Rule</label><input id=\"rule\" placeholder=\"weave_seq\"></div>\n";
  p "        <div class=\"row\"><label for=\"guard-left\">Left Guard</label><input id=\"guard-left\" placeholder=\"<| false <]\"></div>\n";
  p "        <div class=\"row\"><label for=\"guard-right\">Right Guard</label><input id=\"guard-right\" placeholder=\"[> false |>\"></div>\n";
  p "        <div class=\"row\"><label for=\"invariant\">Invariant</label><input id=\"invariant\" placeholder=\"rformula for add_invariant\"></div>\n";
  p "        <div class=\"row\">\n";
  p "          <button class=\"primary\" id=\"btn-apply\">Apply Rewrite</button>\n";
  p "          <button id=\"btn-suggest\">Suggest At Path</button>\n";
  p "          <button id=\"btn-suggest-all\">Suggest All</button>\n";
  p "        </div>\n";
  p "        <div class=\"row\">\n";
  p "          <button id=\"btn-undo\">Undo</button>\n";
  p "          <button id=\"btn-redo\">Redo</button>\n";
  p "          <button id=\"btn-auto\">Auto</button>\n";
  p "          <button class=\"danger\" id=\"btn-reset\">Reset</button>\n";
  p "          <button class=\"good\" id=\"btn-export\">Export</button>\n";
  p "        </div>\n";
  p "        <div id=\"status\"></div>\n";
  p "        <hr style=\"border:none;border-top:1px solid #2d3445;margin:.7rem 0\">\n";
  p "        <div style=\"font-size:.84rem;color:var(--muted);margin-bottom:.4rem\">Suggestions</div>\n";
  p "        <div id=\"suggestions\"></div>\n";
  p "      </section>\n";
  p "      <section class=\"panel\">\n";
  p "        <div class=\"row\" style=\"justify-content:space-between\">\n";
  p "          <span style=\"font-size:.84rem;color:var(--muted)\">Current bicommand</span>\n";
  p "          <a href=\"/help\" target=\"_blank\" rel=\"noopener\">API help</a>\n";
  p "        </div>\n";
  p "        <div class=\"code\" id=\"code\"></div>\n";
  p "      </section>\n";
  p "    </div>\n";
  p "  </div>\n";
  p "  <script>\n";
  p "    const qs = (id) => document.getElementById(id);\n";
  p "    const statusEl = qs('status');\n";
  p "    const setStatus = (msg, ok) => { statusEl.textContent = msg; statusEl.className = ok ? 'ok' : (ok === false ? 'err' : ''); };\n";
  p "\n";
  p "    const enc = encodeURIComponent;\n";
  p "    async function getText(url){ const r = await fetch(url); const t = await r.text(); if(!r.ok) throw new Error(t || ('HTTP ' + r.status)); return t; }\n";
  p "    async function getJson(url){ const t = await getText(url); return JSON.parse(t); }\n";
  p "    async function postText(url){ const r = await fetch(url, {method:'POST'}); const t = await r.text(); if(!r.ok) throw new Error(t || ('HTTP ' + r.status)); return t; }\n";
  p "\n";
  p "    function renderCode(lines){\n";
  p "      const root = qs('code');\n";
  p "      root.textContent = '';\n";
  p "      lines.forEach(item => {\n";
  p "        const row = document.createElement('div'); row.className = 'line';\n";
  p "        const ln = document.createElement('span'); ln.className = 'ln'; ln.textContent = String(item.lineno);\n";
  p "        ln.onclick = async () => { qs('path').value = item.path; await suggestAtPath(); };\n";
  p "        const src = document.createElement('span'); src.className = 'src'; src.textContent = item.text;\n";
  p "        row.appendChild(ln); row.appendChild(src); root.appendChild(row);\n";
  p "      });\n";
  p "    }\n";
  p "\n";
  p "    function renderSuggestions(items){\n";
  p "      const root = qs('suggestions');\n";
  p "      root.textContent = '';\n";
  p "      if(!items.length){ const e = document.createElement('div'); e.textContent = 'No suggestions'; e.style.color = '#9aa8be'; root.appendChild(e); return; }\n";
  p "      items.slice(0, 200).forEach((it) => {\n";
  p "        const box = document.createElement('div'); box.className = 'sitem';\n";
  p "        const left = document.createElement('div');\n";
  p "        left.textContent = 'path=' + (it.path || '') + ' ' + (it.display || it.rule);\n";
  p "        const b = document.createElement('button'); b.textContent = it.needs_input ? 'Fill' : 'Apply'; b.className = 'primary';\n";
  p "        b.onclick = async () => {\n";
  p "          qs('path').value = it.path || ''; qs('rule').value = it.rule || '';\n";
  p "          qs('guard-left').value = it.guard_left || ''; qs('guard-right').value = it.guard_right || '';\n";
  p "          qs('invariant').value = it.formula || '';\n";
  p "          if(it.needs_input){\n";
  p "            const useGuards = it.rule === 'weave_while' || it.rule === 'change_ag';\n";
  p "            (useGuards ? qs('guard-left') : qs('invariant')).focus();\n";
  p "            setStatus(it.rule === 'weave_while'\n";
  p "              ? 'Fields filled \\u2014 enter alignment guards, or leave empty to use defaults, then Apply Rewrite.'\n";
  p "              : 'Fields filled \\u2014 edit the input, then Apply Rewrite.', null);\n";
  p "          } else {\n";
  p "            await applyRewrite();\n";
  p "          }\n";
  p "        };\n";
  p "        box.appendChild(left); box.appendChild(b); root.appendChild(box);\n";
  p "      });\n";
  p "    }\n";
  p "\n";
  p "    async function refreshBicom(){ renderCode(await getJson('/bicom-tree')); }\n";
  p "\n";
  p "    async function applyRewrite(){\n";
  p "      const rule = qs('rule').value.trim();\n";
  p "      const path = qs('path').value.trim();\n";
  p "      const guardLeft = qs('guard-left').value.trim();\n";
  p "      const guardRight = qs('guard-right').value.trim();\n";
  p "      const invariant = qs('invariant').value.trim();\n";
  p "      if(!rule){ setStatus('Provide a rule name.', false); return; }\n";
  p "      let url = '/rewrite?rule=' + enc(rule);\n";
  p "      if(path !== '') url += '&path=' + enc(path);\n";
  p "      if(guardLeft !== '') url += '&guard_left=' + enc(guardLeft);\n";
  p "      if(guardRight !== '') url += '&guard_right=' + enc(guardRight);\n";
  p "      if(invariant !== '') url += '&formula=' + enc(invariant);\n";
  p "      try { await postText(url); await refreshBicom();; setStatus('Rewrite applied.', true); }\n";
  p "      catch (e) { setStatus(String(e.message || e), false); }\n";
  p "    }\n";
  p "\n";
  p "    async function suggestAtPath(){\n";
  p "      const path = qs('path').value.trim();\n";
  p "      const url = path === '' ? '/suggest?path=' : '/suggest?path=' + enc(path);\n";
  p "      try { const s = await getJson(url); renderSuggestions(s); setStatus('Suggestions loaded.', true); }\n";
  p "      catch (e) { setStatus(String(e.message || e), false); }\n";
  p "    }\n";
  p "\n";
  p "    async function suggestAll(){\n";
  p "      try { const s = await getJson('/suggest'); renderSuggestions(s); setStatus('All suggestions loaded.', true); }\n";
  p "      catch (e) { setStatus(String(e.message || e), false); }\n";
  p "    }\n";
  p "\n";
  p "    async function postSimple(path, okMsg){\n";
  p "      try { await postText(path); await refreshBicom();; setStatus(okMsg, true); }\n";
  p "      catch (e) { setStatus(String(e.message || e), false); }\n";
  p "    }\n";
  p "\n";
  p "    qs('btn-apply').onclick = applyRewrite;\n";
  p "    qs('btn-suggest').onclick = suggestAtPath;\n";
  p "    qs('btn-suggest-all').onclick = suggestAll;\n";
  p "    qs('btn-undo').onclick = () => postSimple('/undo', 'Undo applied.');\n";
  p "    qs('btn-redo').onclick = () => postSimple('/redo', 'Redo applied.');\n";
  p "    qs('btn-auto').onclick = () => postSimple('/auto', 'Auto alignment applied.');\n";
  p "    qs('btn-reset').onclick = () => postSimple('/reset', 'Reset to base alignment.');\n";
  p "    qs('btn-export').onclick = async () => {\n";
  p "      try { const t = await postText('/export'); setStatus(t.trim() || 'Exported.', true); }\n";
  p "      catch (e) { setStatus(String(e.message || e), false); }\n";
  p "    };\n";
  p "\n";
  p "    (async () => {\n";
  p "      try { await refreshBicom();; await suggestAtPath(); setStatus('Ready.', true); }\n";
  p "      catch (e) { setStatus(String(e.message || e), false); }\n";
  p "    })();\n";
  p "  </script>\n";
  p "</body>\n</html>\n";
  Buffer.contents buf
