/* Alignment skeleton generated by `whyrel -align -i`.
   left  = M0.tabulate   right = M1.tabulate
   TODO: declare the biinterface and review exported specs. */

bimodule M0_M1_REL (M0 | M1) =

  meth tabulate (n:int|n:int) : (List|List)
    requires { <| n > 0 <] }
    requires { [> n > 0 |> }
    requires { Agree n }
    ensures { Agree result }
    effects  { rd n ;  rw alloc | rd n ;  rw alloc }
  =
    Var  l: List |  in
    Var  |  l: List in
    Var  p: Node |  in
    Var  |  p: Node in
    Var  i: int |  in
    Var  |  i: int in
    (l := new List;
     List(l);
     i := 0;
     while i < n do
       invariant {0 <= i /\ i <= n}
       invariant {rep_closed(l)}
       invariant {let rep = l.rep in p in rep}
       invariant {let s_alloc = old(alloc) in let rep = l.rep in rep # s_alloc}
       rd i ;  rd n ;  rw alloc ;  rw {l}`rep ;  rw {l}`rep`any
       var k : int in
       i := i + 1;
       k := f(i);
       p := new Node;
       Node(p,k);
       var hd : Node in
       hd := l.head;
       p.nxt := hd;
       l.head := p;
       var r : rgn in r := l.rep;
                      l.rep := r union {p}
     done;
     result := l
    | l := new List;
      List(l);
      i := 1;
      while i <= n do
        invariant {1 <= i /\ i <= n + 1}
        invariant {rep_closed(l)}
        invariant {let rep = l.rep in p in rep}
        invariant {let s_alloc = old(alloc) in let rep = l.rep in rep # s_alloc}
        rd i ;  rd n ;  rw alloc ;  rw {l}`rep ;  rw {l}`rep`any
        var k : int in
        k := f(i);
        p := new Node;
        Node(p,k);
        var hd : Node in
        hd := l.head;
        p.nxt := hd;
        l.head := p;
        var r : rgn in r := l.rep;
                       l.rep := r union {p};
                       i := i + 1
      done;
      result := l)
  ;

end
