/* Alignment skeleton generated by `whyrel -align -i`.
   left  = M0.fact   right = M1.fact
   TODO: declare the biinterface and review exported specs. */

bimodule M0_M1_REL (M0 | M1) =

  meth fact (n:int|n:int) : (int|int)
    requires { Both (n >= 0) }
    ensures { Both (result > 0) }
  =
    Var  i: int |  in
    Var  |  i: int in
    (i := 0;
     result := 1;
     while i < n do
       invariant {0 <= i /\ i <= n}
       invariant {result > 0}
       
       i := i + 1;
       result := result * i
     done
    | i := 1;
      result := 1;
      while i <= n do
        invariant {1 <= i /\ i <= n + 1}
        invariant {result > 0}
        
        result := result * i;
        i := i + 1
      done)
  ;

end
